### ISSUE TITLE
How do you execute this code

### ISSUE THREAD

**Issue by t-anton** [AndrewSales/dtd2xml#1]
Hi,

When I run: javac DTD2XML.java in CMD I get:

DTD2XML.java:76: error: cannot find symbol
        private ErrorHandler errorHandler;
                ^
  symbol:   class ErrorHandler
  location: class DTD2XML
DTD2XML.java:77: error: cannot find symbol
        private DeclHandler declHandler;
                ^
  symbol:   class DeclHandler
  location: class DTD2XML
DTD2XML.java:78: error: cannot find symbol
        private LexicalHandler lexicalHandler;
                ^
  symbol:   class LexicalHandler
  location: class DTD2XML
DTD2XML.java:79: error: cannot find symbol
        private DTDHandler dtdHandler;
                ^
  symbol:   class DTDHandler
  location: class DTD2XML
DTD2XML.java:80: error: cannot find symbol
        private DTD dtd;
                ^
  symbol:   class DTD
  location: class DTD2XML
DTD2XML.java:97: error: cannot find symbol
        DTD getDTD() {
        ^
  symbol:   class DTD
  location: class DTD2XML
DTD2XML.java:84: error: cannot find symbol
                errorHandler = new ErrorHandler();
                                   ^
  symbol:   class ErrorHandler
  location: class DTD2XML
DTD2XML.java:86: error: cannot find symbol
                declHandler = new DeclHandler(this);
                                  ^
  symbol:   class DeclHandler
  location: class DTD2XML
DTD2XML.java:89: error: cannot find symbol
                lexicalHandler = new LexicalHandler(this);
                                     ^
  symbol:   class LexicalHandler
  location: class DTD2XML
DTD2XML.java:92: error: cannot find symbol
                dtdHandler = new DTDHandler( this );
                                 ^
  symbol:   class DTDHandler
  location: class DTD2XML
DTD2XML.java:94: error: cannot find symbol
                dtd = new DTD();
                          ^
  symbol:   class DTD
  location: class DTD2XML
Note: DTD2XML.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors

How do I compile the .java code?

Thank you.

**Comment by AndrewSales** [comment]
Hi, thanks for dropping by. I've added a long-overdue executable JAR and some documentation on how to run it. Do let me know if you have any problems.

Fixed by 081f5c1.
